apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linode-object-storage-1
provisioner: csi.linode.com
parameters:
  type: s3fs
  bucket: awx-data
  region: us-ord
allowVolumeExpansion: true
volumeBindingMode: Immediate
