---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  claimRef:
    name: awx-data
    namespace: awx
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.128.111.169
    path: /exports

---
# nfs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-data
  namespace: awx
spec:
  storageClassName: ""
  volumeName: nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
