---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server-0.nfs-server-headless.nfs-server.svc.cluster.local
  share: /exports
mountOptions:
  - nolock
  - soft
  - timeo=30
  - retrans=2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-data
  namespace: awx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi
