apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-data
  namespace: awx
spec:
  storageClassName: linode-object-storage-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
